pull_request_rules:
  - name: approved
    conditions:
      - "#approved-reviews-by>=1"
      - "#status-failure=0"
    actions:
      label:
        add: ["auto-merge"]

  - name: hd
    conditions:
      - author=hardlydifficult
      - "#status-failure=0"
    actions:
      label:
        add: ["auto-merge"]

  - name: dependabot
    conditions:
      - author=dependabot[bot]
      - "#status-failure=0"
    actions:
      label:
        add: ["auto-merge"]

  - name: imgbot
    conditions:
      - author=imgbot[bot]
      - "#status-failure=0"
    actions:
      label:
        add: ["auto-merge"]

  - name: imgbot
    conditions:
      - label=["auto-merge"]
      - "#status-failure>=1"
    actions:
      label:
        remove: ["auto-merge"]

  - name: auto-merge
    conditions:
      - label=auto-merge
      - "#changes-requested-reviews-by=0"
      - "status-success=ci/circleci: testContracts"
      - "status-success=ci/circleci: init"
      - "status-success=ci/circleci: buildWebsite"
      - "status-success=ci/circleci: buildDocs"
      - "status-success=ci/circleci: buildContracts"
      - "status-success=WIP"
    actions:
      merge:
        method: squash
        strict: smart
      delete_head_branch: {}
