pull_request_rules:
  - name: merge if HD
    conditions:
      - author=hardlydifficult
      - "status-success=ci/circleci: testContracts"
      - "status-success=ci/circleci: init"
      - "status-success=ci/circleci: buildWebsite"
      - "status-success=ci/circleci: buildDocs"
      - "status-success=ci/circleci: buildContracts"
      - "status-success=WIP"
    actions:
      merge:
        method: squash
        strict: smart
      delete_head_branch: {}
  - name: merge if dependabot
    conditions:    
      - author=dependabot[bot]
      - "status-success=ci/circleci: testContracts"
      - "status-success=ci/circleci: init"
      - "status-success=ci/circleci: buildWebsite"
      - "status-success=ci/circleci: buildDocs"
      - "status-success=ci/circleci: buildContracts"
      - "status-success=WIP"
    actions:
      merge:
        method: squash
        strict: smart
      delete_head_branch: {}
  - name: merge if imgbot
    conditions:
      - author=imgbot[bot]
      - "status-success=ci/circleci: testContracts"
      - "status-success=ci/circleci: init"
      - "status-success=ci/circleci: buildWebsite"
      - "status-success=ci/circleci: buildDocs"
      - "status-success=ci/circleci: buildContracts"
      - "status-success=WIP"
    actions:
      merge:
        method: squash
        strict: smart
      delete_head_branch: {}
  - name: merge if approved by HD
    conditions:
      - approved-reviews-by=hardlydifficult
      - "#changes-requested-reviews-by=0"
      - "status-success=ci/circleci: testContracts"
      - "status-success=ci/circleci: init"
      - "status-success=ci/circleci: buildWebsite"
      - "status-success=ci/circleci: buildDocs"
      - "status-success=ci/circleci: buildContracts"
      - "status-success=WIP"
    actions:
      merge:
        method: squash
        strict: smart
      delete_head_branch: {}
